apiVersion: v2
name: city-population-api
description: A Helm chart for deploying the City Population API with Elasticsearch on Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: elasticsearch
    version: "8.5.1"
    repository: "https://helm.elastic.co"
    condition: elasticsearch.enabled
